mqtt:
  broker: localhost
  port: 1883
  qos: 1

simulation:
  publish_interval: 2
  peak_hours:
    - [8, 10]    # Morning rush: 8-10 AM
    - [17, 19]   # Evening rush: 5-7 PM
  peak_density_range: [60, 90]
  off_peak_density_range: [10, 40]
  noise_stddev: 5

payload:
  include_sequence_number: true
  include_timestamp: true
  include_queue_length: true
